version: "3.7"

services:
  first_app:
    container_name: first-app-container
    build: .
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
  postgres:
    container_name: first-db-container
    image: "postgres:15"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: azizjon
      POSTGRES_PASSWORD: root
  redis:
    container_name: first-redis-db
    image: "redis"
    restart: "always"
    ports:
      - "6378:6379"